### ISSUE TITLE
Crop shadow

### ISSUE THREAD

**Issue by ai** [animakit/animakit-elastic#1]
Here is block without Elastic: http://i.imgur.com/0XCIbpx.png
And here is with Elastic: http://i.imgur.com/fqELG4z.png

Elastic crops a shadow. Maybe you can use `overflow: hidden` only on resize?

**Comment by askd** [comment]
Thanks for the issue. Now Elastic use `overflow: hidden` during animation only
https://github.com/animakit/animakit-elastic/commit/fbdb94e20f686c4fe1b89734810aa65be40dc0ea
