### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by ai** [animakit/animakit-elastic#3]
We use Elastic in Amplifr like this:

``` haml
AnimakitElastic
    if this.props.links.length && this.isOpenGraph()
      .rich-text_opengraph
        OpenGraph
```

But in Safari we have issue showed on this video: 
https://uploads.intercomcdn.com/i/o/7687288/38161924ca57ad38621b5fd0/video-1467049777.mp4

**Comment by askd** [comment]
Finally fixed ;) https://github.com/animakit/animakit-elastic/commit/347cce51bd003bddacf30145051aaf1fcefdf4d6
